### ISSUE TITLE
Doubly defined label for example listings.

### ISSUE THREAD

**Issue by bamert** [latextemplates/ieee-enhanced#3]
I think the label for the Java listing should be L1 (as referenced in line 288), else label L2 will be doubly defined.

https://github.com/latextemplates/IEEE/blob/e2a0b95034d7d7fe540018b00795688403ed754e/paper-conference.tex#L295

**Comment by koppor** [comment]
Oh, yeah. Could you file a PR?

Nik Bamert <notifications@github.com> schrieb am Mo., 4. März 2019, 14:57:

**Comment by bamert** [comment]
Sure. I added the same fix for all three .tex source files as a pr.
